name: Daily Google Ads Analysis

on:
  schedule:
    # Run daily at 15:00 UTC (9:00 AM MDT)
    - cron: '0 15 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  daily-analysis:
    name: Run Daily Google Ads Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create google-ads.yaml from secrets
        run: |
          cat > google-ads.yaml << EOF
          developer_token: ${{ secrets.GOOGLE_ADS_DEVELOPER_TOKEN }}
          client_id: ${{ secrets.GOOGLE_ADS_CLIENT_ID }}
          client_secret: ${{ secrets.GOOGLE_ADS_CLIENT_SECRET }}
          refresh_token: ${{ secrets.GOOGLE_ADS_REFRESH_TOKEN }}
          login_customer_id: ${{ secrets.GOOGLE_ADS_LOGIN_CUSTOMER_ID }}
          use_proto_plus: True
          EOF
          python -c "import yaml; data=yaml.safe_load(open('google-ads.yaml')); print('YAML config is valid')"
          
      - name: Run daily analysis
        env:
          GOOGLE_ADS_DEVELOPER_TOKEN: ${{ secrets.GOOGLE_ADS_DEVELOPER_TOKEN }}
          GOOGLE_ADS_CLIENT_ID: ${{ secrets.GOOGLE_ADS_CLIENT_ID }}
          GOOGLE_ADS_CLIENT_SECRET: ${{ secrets.GOOGLE_ADS_CLIENT_SECRET }}
          GOOGLE_ADS_REFRESH_TOKEN: ${{ secrets.GOOGLE_ADS_REFRESH_TOKEN }}
          GOOGLE_ADS_LOGIN_CUSTOMER_ID: ${{ secrets.GOOGLE_ADS_LOGIN_CUSTOMER_ID }}
          GOOGLE_ADS_CUSTOMER_ID: ${{ secrets.GOOGLE_ADS_CUSTOMER_ID }}
          GOOGLE_CLIENT_SECRET_FILE: client_secret.json
          # Email configuration
          EMAIL_SMTP_SERVER: ${{ secrets.EMAIL_SMTP_SERVER }}
          EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          EMAIL_REPLY_TO: ${{ secrets.EMAIL_REPLY_TO }}
        run: |
          python examples/quick_analysis.py
          
      - name: Upload analysis artifacts (if any)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: daily-analysis-results-${{ github.run_number }}
          path: |
            *.html
            *.log
            daily_summary_*.html
          retention-days: 7
